[package]
name = "ck3_history_extractor"
version = "0.2.4"
edition = "2021"
authors = ["TCA"]
description = "A tool for generating a encyclopedia from your CK3 save file"
documentation = "https://tca166.github.io/CK3-history-extractor/ck3_history_extractor/"
readme = "./README.md"
homepage = "https://tca166.github.io/CK3-history-extractor/TCA166's%20history/index.html"
repository = "https://github.com/TCA166/CK3-history-extractor"
license = "MIT"
keywords = ["Crusader Kings 3"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minijinja = "2.0.1"
serde = {version="1.0.198" , features=["rc"] }
tempfile = "3.2.0"
syn = "2.0.64"
quote = "1.0"
proc-macro2 = "1.0"
zip = "2.0.0"
image = "0.25.1"
csv = "1.3.0"
plotters = "0.3.3"
tidy-tree = "0.1.0"
atty = "0.2.14"
serde_json = "1.0.118"
dialoguer = "0.11.0"
open = "5.1.4"
rand = "0.8.5"
indicatif = "=0.17.8"
