[package]
name = "ck3_history_extractor"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/bin/x86_64-w64-mingw32-gcc-ar"

[dependencies]
minijinja = "2.0.1"
serde = {version="1.0.198" , features=["rc"] }
tempfile = "3.2.0"
syn = "2.0.64"
quote = "1.0"
proc-macro2 = "1.0"
zip = "2.0.0"
image = "0.25.1"
csv = "1.3.0"
plotters = "0.3.3"
tidy-tree = "0.1.0"
